### ISSUE TITLE
Add a switch "no file verification"

### ISSUE THREAD

**Issue by AnaelMobilia** [bingmann/disk-filltest#1]
Hello,

I'm using the tool to basically wipe a disk.

I made a stub batch file
```
:loop1
disk-filltest.exe -u
goto loop1
```

On this case, i don't care that each loop will check (read_randfiles();) randomness of datas.

I suggest to add one or two switch to : 
  - Allow no randomness verification
  - Allow a loop usage of the software

Bests regards,
Anael

**Comment by bingmann** [comment]
Added in ecefb1aa2371e2907af9ae661621e31e8f84a083
